/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiWeatherForecastGet$Json$Params {
  Date?: string;
  TemperatureC?: number;
  TemperatureF?: number;
  Summary?: string;
  OrderColumn?: string;
  OrderDescending?: boolean;
  Page?: number;
  PageSize?: number;
}

export function apiWeatherForecastGet$Json(http: HttpClient, rootUrl: string, params?: ApiWeatherForecastGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, apiWeatherForecastGet$Json.PATH, 'get');
  if (params) {
    rb.query('Date', params.Date, {});
    rb.query('TemperatureC', params.TemperatureC, {});
    rb.query('TemperatureF', params.TemperatureF, {});
    rb.query('Summary', params.Summary, {});
    rb.query('OrderColumn', params.OrderColumn, {});
    rb.query('OrderDescending', params.OrderDescending, {});
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

apiWeatherForecastGet$Json.PATH = '/api/WeatherForecast';
