/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ChatRequest } from './models/chat-request';
export type { UserMessage } from './models/user-message';
