/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserMessage } from '../../models/user-message';

export interface ApiGeminiChatChatIdPost$Json$Params {
  chatId: string;
      body?: UserMessage
}

export function apiGeminiChatChatIdPost$Json(http: HttpClient, rootUrl: string, params: ApiGeminiChatChatIdPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, apiGeminiChatChatIdPost$Json.PATH, 'post');
  if (params) {
    rb.path('chatId', params.chatId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

apiGeminiChatChatIdPost$Json.PATH = '/api/GeminiChat/{chatId}';
