/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiWeatherForecastGet$Json } from '../fn/weather-forecast/api-weather-forecast-get-json';
import { ApiWeatherForecastGet$Json$Params } from '../fn/weather-forecast/api-weather-forecast-get-json';
import { apiWeatherForecastGet$Plain } from '../fn/weather-forecast/api-weather-forecast-get-plain';
import { ApiWeatherForecastGet$Plain$Params } from '../fn/weather-forecast/api-weather-forecast-get-plain';

@Injectable({ providedIn: 'root' })
export class WeatherForecastService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiWeatherForecastGet()` */
  static readonly ApiWeatherForecastGetPath = '/api/WeatherForecast';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWeatherForecastGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWeatherForecastGet$Plain$Response(params?: ApiWeatherForecastGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return apiWeatherForecastGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWeatherForecastGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWeatherForecastGet$Plain(params?: ApiWeatherForecastGet$Plain$Params, context?: HttpContext): Observable<any> {
    return this.apiWeatherForecastGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWeatherForecastGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWeatherForecastGet$Json$Response(params?: ApiWeatherForecastGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return apiWeatherForecastGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWeatherForecastGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWeatherForecastGet$Json(params?: ApiWeatherForecastGet$Json$Params, context?: HttpContext): Observable<any> {
    return this.apiWeatherForecastGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
